-- Turbine API -- UI namespace (Turbine.UI.*)
-- Auto-generated from Standing Stone Games Turbine API documentation.
-- Use with lua-language-server for Zed editor autocomplete.

-- Namespace declaration (makes this namespace visible in autocomplete)
Turbine.UI = {}

---Specifies a blending method.
---@class Turbine.UI.BlendMode
---@field AlphaBlend number Overlays the source over the destination using the source alpha to interpolate between the source and destination colors.
---@field Color number Performs a blend between a new color generated by applying the hue and saturation of the source and the color value of the destination. The new color and the destination color are then interpolated between using the source alpha.
---@field Grayscale number Compute a new color by copying the max of R,G, and B to all three color channels. This new color is then blended with the destination color based on the source alpha.
---@field Multiply number Computes a new color by multiplying each color channel by the source color channel and then interpolating between the new color and the destination color based on the source alpha. Multiply will never brighten a pixel.
---@field None number None.
---@field Normal number Uses the source color value.
---@field Overlay number Overlays the source over the destination. If the source alpha is zero destination color will remain unchanged, for any other alpha value the source color replaces the destination.
---@field Screen number Compute a new color by multiplying the inverses of each color channel by the inverse of the source color channel and then inverting the result. The new color is then blended with the destination color based on the source alpha. Screen will never darken a pixel.
---@field Undefined number Specifies no blending.
Turbine.UI.BlendMode = {}

---Specifies the alignment of content within a region.
---@class Turbine.UI.ContentAlignment
---@field BottomCenter number Position content at the bottom center of the region.
---@field BottomLeft number Position content at the bottom left of the region.
---@field BottomRight number Position content at the bottom right of the region.
---@field MiddleCenter number Position content at the middle center of the region.
---@field MiddleLeft number Position content at the middle left of the region.
---@field MiddleRight number Position content at the middle right of the region.
---@field TopCenter number Position content at the top center of the region.
---@field TopLeft number Position content at the top left of the region.
---@field TopRight number Position content at the top right of the region.
---@field Undefined number Undefined positioning.
Turbine.UI.ContentAlignment = {}

---Specifies styles that can be applied to fonts.
---@class Turbine.UI.FontStyle
---@field None number No font styles.
---@field Outline number Outlines the font.
Turbine.UI.FontStyle = {}

---Specifies how to perform horizontal layouts.
---@class Turbine.UI.HorizontalLayout
---@field LeftToRight number Layout starting at the left and working right.
---@field RightToLeft number Layout starting at the right and working left.
Turbine.UI.HorizontalLayout = {}

---Defines one of the mouse buttons.
---@class Turbine.UI.MouseButton
---@field Left number Specifies the left button.
---@field Middle number Specifies the middle button.
---@field None number Specifies no mouse button.
---@field Right number Specifies the right button.
Turbine.UI.MouseButton = {}

---Specifies orientation of objects.
---@class Turbine.UI.Orientation
---@field Horizontal number Specifies a horizontal layout.
---@field Vertical number Specifies a vertical layout.
Turbine.UI.Orientation = {}

---Specifies how to perform vertical layouts.
---@class Turbine.UI.VerticalLayout
---@field BottomToTop number Layout starting at the bottom and working up.
---@field TopToBottom number Layout starting at the top and working down.
Turbine.UI.VerticalLayout = {}

---A simple button control.
---@class Turbine.UI.Button : Turbine.UI.Label
---@field Click fun(sender: table, args: table) Event fired when the user clicks on the button.
---@field EnabledChanged fun(sender: table, args: table) Event fired when the enabled state of the control changes.
Turbine.UI.Button = {}

---A control used to indicate a boolean state.
---@class Turbine.UI.CheckBox : Turbine.UI.Label
---@field CheckedChanged fun(sender: table, args: table) Event fired when the checked state changes.
---@field EnabledChanged fun(sender: table, args: table) Event fired when the enabled state of the control changes.
Turbine.UI.CheckBox = {}

---Gets the alignment of the check within the check box.
---@return number # The alignment of the check in the check box.
function Turbine.UI.CheckBox:GetCheckAlignment() end

---Gets a flag indicating if the check box is checked.
---@return boolean # True if the check box is checked.
function Turbine.UI.CheckBox:IsChecked() end

---Sets the alignment of the check within the check box.
---@param value number The alignment of the check in the check box.
function Turbine.UI.CheckBox:SetCheckAlignment(value) end

---Sets a flag indicating if the check box is checked.
---@param value boolean True to check the check box.
function Turbine.UI.CheckBox:SetChecked(value) end

---Represents a 4 channel color with red, green, blue, and alpha.
---@class Turbine.UI.Color : Turbine.Object
Turbine.UI.Color = {}

---Initializes a new color.
---@overload fun(r: number, g: number, b: number): Turbine.UI.Color
---@overload fun(a: number, r: number, g: number, b: number): Turbine.UI.Color
---@return Turbine.UI.Color
function Turbine.UI.Color() end

---Defines a menu that can be displayed to the user.
---@class Turbine.UI.ContextMenu : Turbine.Object
Turbine.UI.ContextMenu = {}

---Closes the menu if it is displayed.
function Turbine.UI.ContextMenu:Close() end

---Gets the menu items collection.
---@return Turbine.UI.MenuItemList # Returns the menu items collection.
function Turbine.UI.ContextMenu:GetItems() end

---Displays the menu.
function Turbine.UI.ContextMenu:ShowMenu() end

---Displays the menu.
---@param x number The x coordinate to display the menu at.
---@param y number The y coordinate to display the menu at.
function Turbine.UI.ContextMenu:ShowMenuAt(x, y) end

---The base control class for all available user interface elements.
---@class Turbine.UI.Control : Turbine.Object
---@field DragDrop fun(sender: table, args: table) Event fired when a drag drop operation is completed.
---@field DragEnter fun(sender: table, args: table) Event fired when a drag drop operation enters the control.
---@field DragLeave fun(sender: table, args: table) Event fired when a drag drop operation leaves the control.
---@field DragStart fun(sender: table, args: table) Event fired when a drag drop operation starts the control.
---@field EnabledChanged fun(sender: table, args: table) Event fired when the enabled state of the control changes.
---@field FocusGained fun(sender: table, args: table) Event fired when the control gains focus.
---@field FocusLost fun(sender: table, args: table) Event fired when the control loses focus.
---@field KeyDown fun(sender: table, args: table) Event fired when a key is pressed down.
---@field KeyUp fun(sender: table, args: table) Event fired when a key is released.
---@field MouseClick fun(sender: table, args: table) Event fired when a mouse button is clicked.
---@field MouseDoubleClick fun(sender: table, args: table) Event fired when a mouse button is double clicked.
---@field MouseDown fun(sender: table, args: table) Event fired when a mouse button is pressed.
---@field MouseEnter fun(sender: table, args: table) Event fired when the mouse enters the control.
---@field MouseHover fun(sender: table, args: table) Event fired when the mouse is hovering over the control.
---@field MouseLeave fun(sender: table, args: table) Event fired when the mouse leaves the cotnrol.
---@field MouseMove fun(sender: table, args: table) Event fired when the mouse moves.
---@field MouseUp fun(sender: table, args: table) Event fired when a mouse button is released.
---@field MouseWheel fun(sender: table, args: table) Event fired when a mouse wheel moves.
---@field PositionChanged fun(sender: table, args: table) Event fired when the position of the control changes.
---@field SizeChanged fun(sender: table, args: table) Event fired when the size of the control changes.
---@field Update fun(sender: table, args: table) Event fired every frame when WantsUpdates is enabled.
---@field VisibleChanged fun(sender: table, args: table) Event fired when the visible state of the control changes.
Turbine.UI.Control = {}

---Request that the control take focus.
function Turbine.UI.Control:Focus() end

---Gets if the control supports drop operations from drag and drop.
---@return boolean # True if the control will handle drag and drop events.
function Turbine.UI.Control:GetAllowDrop() end

---Gets the solid background color of the control.
---@return Turbine.UI.Color # Returns a color table containing the current control background color.
function Turbine.UI.Control:GetBackColor() end

---Gets the blend mode applied to the background color.
---@return number # Returns one of the values from BlendMode that describes how to blend the background color.
function Turbine.UI.Control:GetBackColorBlendMode() end

---Gets the background graphic of the control.
---@return Turbine.UI.Graphic # The background graphic of the control..
function Turbine.UI.Control:GetBackground() end

---Gets the blend mode applied to the background image.
---@return number # Returns one of the values from BlendMode that describes how to blend the background image.
function Turbine.UI.Control:GetBlendMode() end

---Gets the list of child controls.
---@return Turbine.UI.ControlList # The list of child controls.
function Turbine.UI.Control:GetControls() end

---Gets the height of the control.
---@return number # The height of the control.
function Turbine.UI.Control:GetHeight() end

---Gets the left coordinate of the control.
---@return number # The left position of the window.
function Turbine.UI.Control:GetLeft() end

---Gets the mouse position relative to this control.
---@return number, number # The mouse position relative to this control.
function Turbine.UI.Control:GetMousePosition() end

---Gets the opacity of the window.
---@return number # A value of 0 to 1 indicating how transparent the window is.
function Turbine.UI.Control:GetOpacity() end

---Gets the parent of the control.
---@return Turbine.UI.Control # The parent of the control.
function Turbine.UI.Control:GetParent() end

---Gets the position of the control.
---@return number, number # List of two elements containing the left and top positions of the control.
function Turbine.UI.Control:GetPosition() end

---Gets the size of the control.
---@return number, number # The width and height as a pair of integers.
function Turbine.UI.Control:GetSize() end

---Gets the top coordinate of the window.
---@return number # The top position of the window.
function Turbine.UI.Control:GetTop() end

---Gets a flag indicating if the control wants to receive key events.
---@return boolean # True if the control wants to receive key events.
function Turbine.UI.Control:GetWantsKeyEvents() end

---Gets the flag indicating if the control wants to receive Update notifications.
---@return boolean # True if the control is receiving update notifications.
function Turbine.UI.Control:GetWantsUpdates() end

---Gets the width of the control.
---@return number # The width of the control.
function Turbine.UI.Control:GetWidth() end

---Gets the Z ordering index of the control.
---@return number # The current Z order of the control.
function Turbine.UI.Control:GetZOrder() end

---Returns true if the control has focus.
---@return boolean # Returns true if the control has focus.
function Turbine.UI.Control:HasFocus() end

---Test if the alt key is pressed.
---@return boolean # True if the alt key is pressed.
function Turbine.UI.Control.IsAltKeyDown() end

---Test if the control key is pressed.
---@return boolean # True if the control key is pressed.
function Turbine.UI.Control.IsControlKeyDown() end

---Gets a flag indicating if the control is displayed.
---@return boolean # True if the control is displayed.
function Turbine.UI.Control:IsDisplayed() end

---Gets a flag indicating if the control is enabled.
---@return boolean # True if the control is enabled.
function Turbine.UI.Control:IsEnabled() end

---Gets a flag indicating if the mouse will see this control.
---@return boolean # True if the control processing mouse messages.
function Turbine.UI.Control:IsMouseVisible() end

---Test if the shift key is pressed.
---@return boolean # True if the shift key is pressed.
function Turbine.UI.Control.IsShiftKeyDown() end

---Gets a flag indicating if the control is visible.
---@return boolean # True if the control is visible.
function Turbine.UI.Control:IsVisible() end

---Converts a coordinate from control space to screen space.
---@param x number The X coordinate.
---@param y number The Y coordinate.
---@return number, number # The control coordinate for the screen coordinate specified.
function Turbine.UI.Control:PointToClient(x, y) end

---Converts a coordinate from control space to screen space.
---@param x number The X coordinate.
---@param y number The Y coordinate.
---@return number, number # The screen coordinate for the control coordinate specified.
function Turbine.UI.Control:PointToScreen(x, y) end

---Sets if the control supports drop operations from drag and drop.
---@param value boolean True if the control will handle drag and drop events.
function Turbine.UI.Control:SetAllowDrop(value) end

---Sets the background color of the control.
---@param value Turbine.UI.Color The new background color for the control.
function Turbine.UI.Control:SetBackColor(value) end

---Sets the blend mode applied to the background color.
---@param value number The new background color blend mode.
function Turbine.UI.Control:SetBackColorBlendMode(value) end

---Sets the background image of the control.
---@param backgroundImage any The path or id of the image to set the background of the control to.
function Turbine.UI.Control:SetBackground(backgroundImage) end

---Sets the blend mode applied to the background image.
---@param value number The new background blend mode.
function Turbine.UI.Control:SetBlendMode(value) end

---Sets a flag indicating if the control is enabled.
---@param value boolean True if the control is to be enabled, false to disable.
function Turbine.UI.Control:SetEnabled(value) end

---Sets the height of the control.
---@param value number The height of the control.
function Turbine.UI.Control:SetHeight(value) end

---Sets the left coordinate of the window.
---@param value number The left position of the window.
function Turbine.UI.Control:SetLeft(value) end

---Gets a flag indicating if the mouse will see this control.
---@param value boolean True if the control should process mouse messages.
function Turbine.UI.Control:SetMouseVisible(value) end

---Sets the opacity of the window.
---@param value number
function Turbine.UI.Control:SetOpacity(value) end

---Sets the parent of the control.
---@param value Turbine.UI.Control The desired parent. If this is nil, the control will be unparented.
function Turbine.UI.Control:SetParent(value) end

---Sets the position of the control.
---@param left number The left position of the control.
---@param top number The top position of the control.
function Turbine.UI.Control:SetPosition(left, top) end

---Sets the size of the control.
---@param width number The desired width.
---@param height number The desired height.
function Turbine.UI.Control:SetSize(width, height) end

---Sets the top coordinate of the window.
---@param value number The top position of the window.
function Turbine.UI.Control:SetTop(value) end

---Sets the visible flag of a control.
---@param value boolean The new visibility state. True to show, false to hide.
function Turbine.UI.Control:SetVisible(value) end

---Sets a flag indicating if the control wants to receive key events.
---@param value boolean True if the control wants to receive key events.
function Turbine.UI.Control:SetWantsKeyEvents(value) end

---Sets the flag indicating if the cotnrol wants to receive update notifications.
---@param value boolean True to enable update calls.
function Turbine.UI.Control:SetWantsUpdates(value) end

---Sets the width of the control.
---@param value number The width of the control.
function Turbine.UI.Control:SetWidth(value) end

---Sets the Z order of the control.
---@param value number The new Z order of the control.
function Turbine.UI.Control:SetZOrder(value) end

---Defines a list of controls.
---@class Turbine.UI.ControlList : Turbine.Object
Turbine.UI.ControlList = {}

---Adds a menu item.
---@param item Turbine.UI.Control The menu item to add.
function Turbine.UI.ControlList:Add(item) end

---Clears the items from the list.
function Turbine.UI.ControlList:Clear() end

---Test is the list contains a specific menu item.
---@param item Turbine.UI.Control The item to check for.
---@return boolean # True if the item is contained in the list.
function Turbine.UI.ControlList:Contains(item) end

---Gets the item at the specified index.
---@param index number The index of the item to retrieve.
---@return Turbine.UI.Control # The menu item at the specified index.
function Turbine.UI.ControlList:Get(index) end

---Gets the number of menu items.
---@return number # The number of menu items.
function Turbine.UI.ControlList:GetCount() end

---Gets the index of a menu item in the list.
---@param item Turbine.UI.Control The item to get the index of.
---@return number # The index of the item in the list or -1 if it does not exist in the list.
function Turbine.UI.ControlList:IndexOf(item) end

---Inserts a menu item at a given index.
---@param index number The index to insert the item at.
---@param item Turbine.UI.Control The menu item to insert.
function Turbine.UI.ControlList:Insert(index, item) end

---Removes a menu item from the list.
---@param item Turbine.UI.Control The item to remove.
function Turbine.UI.ControlList:Remove(item) end

---Removes a menu item at the specified index.
---@param index number The index of the item to remove.
function Turbine.UI.ControlList:RemoveAt(index) end

---Sets the menu item at the specified index.
---@param index number The index of the menu item to set.
---@param item Turbine.UI.Control The item to set.
function Turbine.UI.ControlList:Set(index, item) end

---Provides display information.
---@class Turbine.UI.Display
Turbine.UI.Display = {}

---Gets the height of the display.
---@return number # The display height.
function Turbine.UI.Display.GetHeight() end

---Gets the position of the mouse.
---@return number, number # The position of the mouse in screen coordinates.
function Turbine.UI.Display.GetMousePosition() end

---Gets the X position of the mouse.
---@return number # The X position of the mouse in screen coordinates.
function Turbine.UI.Display.GetMouseX() end

---Gets the Y position of the mouse.
---@return number # The Y position of the mouse in screen coordinates.
function Turbine.UI.Display.GetMouseY() end

---Gets the size of the display window for the game.
---@return number, number # The horizontal and vertical resolution as two values.
function Turbine.UI.Display.GetSize() end

---Gets the width of the display.
---@return number # The display width.
function Turbine.UI.Display.GetWidth() end

---Container for information about drag drop events.
---@class Turbine.UI.DragDropInfo : Turbine.Object
Turbine.UI.DragDropInfo = {}

---@return boolean # True if the drag drop was successful.
function Turbine.UI.DragDropInfo:IsSuccessful() end

---@param value boolean True if the drag drop was successful.
function Turbine.UI.DragDropInfo:SetSuccessful(value) end

---Represents a graphic resources that is loaded from the DAT files or from disk.
---@class Turbine.UI.Graphic : Turbine.Object
Turbine.UI.Graphic = {}

---Constructs an empty graphics.
---@overload fun(dataId: any): Turbine.UI.Graphic
---@overload fun(filename: string): Turbine.UI.Graphic
---@return Turbine.UI.Graphic
function Turbine.UI.Graphic() end

---A simple label for displaying text.
---@class Turbine.UI.Label : Turbine.UI.ScrollableControl
Turbine.UI.Label = {}

---Appends text to the end of the label.
---@param value string The text to append.
function Turbine.UI.Label:AppendText(value) end

---Deselects all the text in the control.
function Turbine.UI.Label:DeselectAll() end

---Gets the current font.
---@return number # The current font.
function Turbine.UI.Label:GetFont() end

---Gets the font style.
---@return number # The current font style.
function Turbine.UI.Label:GetFontStyle() end

---Gets the foreground color.
---@return Turbine.UI.Color # The color used for drawing the text.
function Turbine.UI.Label:GetForeColor() end

---Gets the text outline color.
---@return Turbine.UI.Color # The color used for outlining the text.
function Turbine.UI.Label:GetOutlineColor() end

---Gets the selected text of the label.
---@return string # The selected text of the label.
function Turbine.UI.Label:GetSelectedText() end

---Gets the length of the selected text.
---@return number # The length of the selected text.
function Turbine.UI.Label:GetSelectionLength() end

---Gets the position of the selection start.
---@return number # The position of the selection start.
function Turbine.UI.Label:GetSelectionStart() end

---Gets the text of the label.
---@return string # The text of the label.
function Turbine.UI.Label:GetText() end

---Gets the alignment of the text within the label.
---@return number # The alignment of the text.
function Turbine.UI.Label:GetTextAlignment() end

---Gets the length of the text of the label.
---@return number # The length of the text of the label.
function Turbine.UI.Label:GetTextLength() end

---Inserts text into the label at the current cursor position.
---@param value string The text to insert.
function Turbine.UI.Label:InsertText(value) end

---Gets a flag indicating if markup is enabled for the label.
---@return boolean # True if text markup is enabled.
function Turbine.UI.Label:IsMarkupEnabled() end

---Gets if the label is set to display multiple lines.
---@return boolean # True if the label will display on multiple lines.
function Turbine.UI.Label:IsMultiline() end

---Gets a flag indicating if the text in the label is selectable.
---@return boolean # True if the text in the label is selectable.
function Turbine.UI.Label:IsSelectable() end

---Selects all the text in the control.
function Turbine.UI.Label:SelectAll() end

---Sets the current font.
---@param value number The desired font.
function Turbine.UI.Label:SetFont(value) end

---Sets the font style.
---@param value number The desired font style.
function Turbine.UI.Label:SetFontStyle(value) end

---Sets the foreground color.
---@param value Turbine.UI.Color The color used for drawing the text.
function Turbine.UI.Label:SetForeColor(value) end

---Sets a flag indicating if markup is enabled for the label.
---@param value boolean Flag indicating if markup should be enabled.
function Turbine.UI.Label:SetMarkupEnabled(value) end

---Sets if the label should display on multiple lines.
---@param value boolean True to make the label multiline.
function Turbine.UI.Label:SetMultiline(value) end

---Sets the text outline color.
---@param value Turbine.UI.Color The color used for outlining the text.
function Turbine.UI.Label:SetOutlineColor(value) end

---Sets a flag indicating if the text in the label can be selected.
---@param value boolean True to enable selection of text in the label.
function Turbine.UI.Label:SetSelectable(value) end

---Replaces the selected text.
---@param value string The text to replace the selected text with.
function Turbine.UI.Label:SetSelectedText(value) end

---Sets the selected text.
---@param start number The starting position to select.
---@param length number The length of text to select.
function Turbine.UI.Label:SetSelection(start, length) end

---Sets the length of the selected text.
---@param value number The length of the selected text.
function Turbine.UI.Label:SetSelectionLength(value) end

---Sets the position of the selection start.
---@param value number The position of the selection start.
function Turbine.UI.Label:SetSelectionStart(value) end

---Sets the text of the label.
---@param value string The text of the label.
function Turbine.UI.Label:SetText(value) end

---Sets the alignment of the text within the label.
---@param value number The alignment of the text.
function Turbine.UI.Label:SetTextAlignment(value) end

---A simple list box for laying out child controls in a list.
---@class Turbine.UI.ListBox : Turbine.UI.ScrollableControl
---@field ItemAdded fun(sender: table, args: table) Event fired when an item is added.
---@field ItemRemoved fun(sender: table, args: table) Event fired when an item is removed.
---@field SelectedIndexChanged fun(sender: table, args: table) Event fired when the selected index has changed.
Turbine.UI.ListBox = {}

---Adds an item to the list box.
---@param item Turbine.UI.Control The item to add.
function Turbine.UI.ListBox:AddItem(item) end

---Clears all the items from the listbox.
function Turbine.UI.ListBox:ClearItems() end

---Test is the list box contains an item.
---@param item Turbine.UI.Control The item to check for.
---@return boolean # True if the list box contains the specified item.
function Turbine.UI.ListBox:ContainsItem(item) end

---Ensures that the specified item is visible.
---@param index number The one-based index of the item to scroll into view.
function Turbine.UI.ListBox:EnsureVisible(index) end

---Gets the flag indicating that the draw order should be flipped.
---@return boolean # True if flipped layout is enabled.
function Turbine.UI.ListBox:GetFlippedLayout() end

---Gets the flag indicating that cell alignment is ignored during rendering.
---@return boolean # True if cell alignment is ignored.
function Turbine.UI.ListBox:GetIgnoreCellAlignment() end

---Gets the item at the specified index.
---@param index number The index of the item to get.
---@return Turbine.UI.Control # The item at the specified index.
function Turbine.UI.ListBox:GetItem(index) end

---Gets the item at the specified position.
---@param x number
---@param y number
---@return Turbine.UI.Control # The item at the specified location in the list box otherwise if no item is there this will return nil.
function Turbine.UI.ListBox:GetItemAt(x, y) end

---Gets the number of items in the list box.
---@return number # The number of items in the list box.
function Turbine.UI.ListBox:GetItemCount() end

---Gets the maximum number of columns a listbox can display.
---@return number # The maximum number of columns a listbox can display per row.
function Turbine.UI.ListBox:GetMaxColumns() end

---Gets the maximum number of items per line.
---NOTE: Deprecated - Use GetMaxColumns() and GetMaxRows() instead.
---@return number # The maximum number of elements per line.
function Turbine.UI.ListBox:GetMaxItemsPerLine() end

---Gets the maximum number of rows a listbox can display.
---@return number # The maximum number of rows a listbox can display.
function Turbine.UI.ListBox:GetMaxRows() end

---Gets the orientation of elements in the listbox.
---@return number # Returns either Horizontal or Vertical, indicating which direction elements are arranged in the listbox.
function Turbine.UI.ListBox:GetOrientation() end

---Gets the flag indicating if the listbox should fill in reverse.
---@return boolean # True if reverse fill is enabled.
function Turbine.UI.ListBox:GetReverseFill() end

---Gets the selected index.
---@return number # The currently selected index or 0 if no item is selected.
function Turbine.UI.ListBox:GetSelectedIndex() end

---Gets the currently selected item.
---@return Turbine.UI.Control # The currently selected item.
function Turbine.UI.ListBox:GetSelectedItem() end

---Gets the number of pixels to indent wrapped rows in a horizontal listbox or wrapped columns in a vertical listbox.
---@return number # The number of pixels to indent wrapped rows or columns.
function Turbine.UI.ListBox:GetWrapIndentAmount() end

---Gets the index of an item in the list box.
---@param item Turbine.UI.Control The item to get the index of.
---@return number # The index of the item if it is in the list box otherwise -1.
function Turbine.UI.ListBox:IndexOfItem(item) end

---Inserts an item to the list box.
---@param index number The index to insert the item at.
---@param item Turbine.UI.Control The item to insert.
function Turbine.UI.ListBox:InsertItem(index, item) end

---Removes an item from the list box.
---@param item Turbine.UI.Control The item to remove.
function Turbine.UI.ListBox:RemoveItem(item) end

---Removes an item at the specified index.
---@param index number The index of the item to remove.
function Turbine.UI.ListBox:RemoveItemAt(index) end

---Sets the flag indicating that the draw order should be flipped.
---@param value boolean True to enable layout flipping.
function Turbine.UI.ListBox:SetFlippedLayout(value) end

---Sets the flag indicating that cell alignment is ignored during rendering.
---@param value boolean True to ignore cell alignment.
function Turbine.UI.ListBox:SetIgnoreCellAlignment(value) end

---Sets the item at the specified index.
---@param index number The index of the item to set.
---@param item Turbine.UI.Control The item to set at the specified index.
function Turbine.UI.ListBox:SetItem(index, item) end

---Sets the maximum number of columns a listbox can display.
---@param value number The maximum number of columns to display.
function Turbine.UI.ListBox:SetMaxColumns(value) end

---Sets the maximum number of items per line.
---NOTE: Deprecated - Use SetMaxColumns( i_value ) and SetMaxRows( i_value ) instead.
---@param value number The maximum number of elements per line.
function Turbine.UI.ListBox:SetMaxItemsPerLine(value) end

---Sets the maximum number of rows a listbox can display.
---@param value number The maximum number of rows to display.
function Turbine.UI.ListBox:SetMaxRows(value) end

---Sets the orientation of elements in the listbox.
---@param value number Sets the direction in which elements are laid out in the listbox.
function Turbine.UI.ListBox:SetOrientation(value) end

---Sets the flag indicating that the listbox should fill in reverse.
---@param value boolean True to enable reverse fill.
function Turbine.UI.ListBox:SetReverseFill(value) end

---Sets the selected index.
---@param index number The index to select.
function Turbine.UI.ListBox:SetSelectedIndex(index) end

---Sets the currently selected item.
---@param item Turbine.UI.Control The item to select.
function Turbine.UI.ListBox:SetSelectedItem(item) end

---Sets the number of pixels to indent wrapped rows in a horizontal listbox or wrapped columns in a vertical listbox.
---@param value number The number of pixels to indent wrapped rows or columns.
function Turbine.UI.ListBox:SetWrapIndentAmount(value) end

---Sorts the elements in the list box.
---@param sortMethod Object The function used to sort the elements in the list box.
function Turbine.UI.ListBox:Sort(sortMethod) end

---Defines a menu item.
---@class Turbine.UI.MenuItem : Turbine.Object
---@field Click fun(sender: table, args: table) Event fired when a user clicks on the menu item.
Turbine.UI.MenuItem = {}

---Gets the text of the menu item.
---@return string # The text displayed for the item.
function Turbine.UI.MenuItem:GetText() end

---Gets a flag indicating if the menu item is checked.
---@return boolean # True if the menu item is checked.
function Turbine.UI.MenuItem:IsChecked() end

---Gets a flag indicating if the menu item is enabled.
---@return boolean # True if the menu item is enabled.
function Turbine.UI.MenuItem:IsEnabled() end

---Constructs a new menu item.
---@param text string The text to use for the menu item.
---@overload fun(text: string, enabled: boolean): Turbine.UI.MenuItem
---@overload fun(text: string, enabled: boolean, checked: boolean): Turbine.UI.MenuItem
---@return Turbine.UI.MenuItem
function Turbine.UI.MenuItem(text) end

---Sets a flag indicating if the menu item is checked.
---@param value boolean True if the menu item is checked.
function Turbine.UI.MenuItem:SetChecked(value) end

---Sets a flag indicating if the menu item is enabled.
---@param value boolean True if the menu item is enabled.
function Turbine.UI.MenuItem:SetEnabled(value) end

---Sets the text of the menu item.
---@param value string The text displayed for the item.
function Turbine.UI.MenuItem:SetText(value) end

---Defines a list of menu items.
---@class Turbine.UI.MenuItemList : Turbine.Object
Turbine.UI.MenuItemList = {}

---Adds a menu item.
---@param item Turbine.UI.MenuItem The menu item to add.
function Turbine.UI.MenuItemList:Add(item) end

---Clears the items from the list.
function Turbine.UI.MenuItemList:Clear() end

---Test is the list contains a specific menu item.
---@param item Turbine.UI.MenuItem The item to check for.
---@return boolean # True if the item is contained in the list.
function Turbine.UI.MenuItemList:Contains(item) end

---Gets the item at the specified index.
---@param index number The index of the item to retrieve.
---@return Turbine.UI.MenuItem # The menu item at the specified index.
function Turbine.UI.MenuItemList:Get(index) end

---Gets the number of menu items.
---@return number # The number of menu items.
function Turbine.UI.MenuItemList:GetCount() end

---Gets the index of a menu item in the list.
---@param item Turbine.UI.MenuItem The item to get the index of.
---@return number # The index of the item in the list or -1 if it does not exist in the list.
function Turbine.UI.MenuItemList:IndexOf(item) end

---Inserts a menu item at a given index.
---@param index number The index to insert the item at.
---@param item Turbine.UI.MenuItem The menu item to insert.
function Turbine.UI.MenuItemList:Insert(index, item) end

---Removes a menu item from the list.
---@param item Turbine.UI.MenuItem The item to remove.
function Turbine.UI.MenuItemList:Remove(item) end

---Removes a menu item at the specified index.
---@param index number The index of the item to remove.
function Turbine.UI.MenuItemList:RemoveAt(index) end

---Sets the menu item at the specified index.
---@param index number The index of the menu item to set.
---@param item Turbine.UI.MenuItem The item to set.
function Turbine.UI.MenuItemList:Set(index, item) end

---A control for scrolling contents.
---@class Turbine.UI.ScrollBar : Turbine.UI.Control
---@field OrientationChanged fun(sender: table, args: table) Event fired when the orientation has changed.
---@field ValueChanged fun(sender: table, args: table) Event fired when the value has changed.
Turbine.UI.ScrollBar = {}

---Gets the button that is used to decrement the value.
---@return Object # The button to decrement the value.
function Turbine.UI.ScrollBar:GetDecrementButton() end

---Gets the button that is used to increment the value.
---@return Object # The button to increment the value.
function Turbine.UI.ScrollBar:GetIncrementButton() end

---Gets the large change value of the scrollbar.
---@return number # The large change value of the scroll bar.
function Turbine.UI.ScrollBar:GetLargeChange() end

---Gets the maximum value of the scrollbar.
---@return number # The maximum value of the scroll bar.
function Turbine.UI.ScrollBar:GetMaximum() end

---Gets the minimum value of the scrollbar.
---@return number # The minimum value of the scroll bar.
function Turbine.UI.ScrollBar:GetMinimum() end

---Gets the orientation of the scroll bar.
---@return number # The current orientation of the scrollbar.
function Turbine.UI.ScrollBar:GetOrientation() end

---Gets the small change value of the scrollbar.
---@return number # The small change value of the scroll bar.
function Turbine.UI.ScrollBar:GetSmallChange() end

---Gets the thumb button.
---@return Object # The button to drag the value.
function Turbine.UI.ScrollBar:GetThumbButton() end

---Gets the current value of the scrollbar.
---@return number # The current value of the scroll bar.
function Turbine.UI.ScrollBar:GetValue() end

---Sets the button that is used to decrement the value.
---@param value Object The button to decrement the value.
function Turbine.UI.ScrollBar:SetDecrementButton(value) end

---Sets the button that is used to increment the value.
---@param value Object The button to increment the value.
function Turbine.UI.ScrollBar:SetIncrementButton(value) end

---Sets the large change value of the scrollbar.
---@param value number The large change value of the scroll bar.
function Turbine.UI.ScrollBar:SetLargeChange(value) end

---Sets the maximum value of the scrollbar.
---@param value number The maximum value of the scroll bar.
function Turbine.UI.ScrollBar:SetMaximum(value) end

---Sets the minimum value of the scrollbar.
---@param value number The minimum value of the scroll bar.
function Turbine.UI.ScrollBar:SetMinimum(value) end

---Sets the orientation of the scroll bar.
---@param value number The orientation of the scrollbar.
function Turbine.UI.ScrollBar:SetOrientation(value) end

---Sets the small change value of the scrollbar.
---@param value number The small change value of the scroll bar.
function Turbine.UI.ScrollBar:SetSmallChange(value) end

---Sets the thumb button.
---@param value Object The button to drag the value.
function Turbine.UI.ScrollBar:SetThumbButton(value) end

---Sets the current value of the scrollbar.
---@param value number The current value of the scroll bar.
function Turbine.UI.ScrollBar:SetValue(value) end

---Defines a control that can be scrolled.
---@class Turbine.UI.ScrollableControl : Turbine.UI.Control
Turbine.UI.ScrollableControl = {}

---Gets the horizontal scroll bar.
---@return Object # The horizontal scroll bar.
function Turbine.UI.ScrollableControl:GetHorizontalScrollBar() end

---Gets the vertical scroll bar.
---@return Object # The vertical scroll bar.
function Turbine.UI.ScrollableControl:GetVerticalScrollBar() end

---Sets the horizontal scroll bar.
---@param value Object The horizontal scroll bar to use.
function Turbine.UI.ScrollableControl:SetHorizontalScrollBar(value) end

---Sets the vertical scroll bar.
---@param value Object The vertical scroll bar to use.
function Turbine.UI.ScrollableControl:SetVerticalScrollBar(value) end

---A control for inputting text.
---@class Turbine.UI.TextBox : Turbine.UI.Label
---@field EnabledChanged fun(sender: table, args: table) Event fired when the enabled state of the control changes.
---@field TextChanged fun(sender: table, args: table) Event fired when the text is changed.
Turbine.UI.TextBox = {}

---Gets a flag indicating if the text in the control is read only.
---@return boolean # True if the control is read only.
function Turbine.UI.TextBox:IsReadOnly() end

---Sets a flag indicating if the text in the control is read only.
---@param value boolean True to set the control to read only.
function Turbine.UI.TextBox:SetReadOnly(value) end

---The base for any element that will be part of a tree view control.
---@class Turbine.UI.TreeNode : Turbine.UI.Control
---@field SelectedChanged fun(sender: table, args: table) Event fired when the selected state of the node has changed.
Turbine.UI.TreeNode = {}

---Collapses the node.
function Turbine.UI.TreeNode:Collapse() end

---Collapses all the child tree nodes.
function Turbine.UI.TreeNode:CollapseAll() end

---Ensures that the node is visible within its tree.
function Turbine.UI.TreeNode:EnsureVisible() end

---Expands the node.
function Turbine.UI.TreeNode:Expand() end

---Expands all the child tree nodes.
function Turbine.UI.TreeNode:ExpandAll() end

---Gets the child nodes list.
---@return Turbine.UI.TreeNodeList # The list of child nodes.
function Turbine.UI.TreeNode:GetChildNodes() end

---Gets the parent node of this node.
---@return Turbine.UI.TreeNode # The parent TreeNode for this node. If this is a root node this will return nil.
function Turbine.UI.TreeNode:GetParentNode() end

---Gets a flag indicating if this node is currently expanded.
---@return boolean # True if this node is currently expanded.
function Turbine.UI.TreeNode:IsExpanded() end

---Return true if this node is currently selected.
---@return boolean # True if this node is currently selected.
function Turbine.UI.TreeNode:IsSelected() end

---Sets the flag indicating if this node is currently expanded.
---@param value boolean True if this node should be expanded.
function Turbine.UI.TreeNode:SetExpanded(value) end

---Defines a list of controls.
---@class Turbine.UI.TreeNodeList : Turbine.Object
Turbine.UI.TreeNodeList = {}

---Adds a tree node.
---@param node Turbine.UI.TreeNode The tree node to add.
function Turbine.UI.TreeNodeList:Add(node) end

---Clears the nodes from the list.
function Turbine.UI.TreeNodeList:Clear() end

---Test is the list contains a specific tree node.
---@param node Turbine.UI.TreeNode The node to check for.
---@return boolean # True if the node is contained in the list.
function Turbine.UI.TreeNodeList:Contains(node) end

---Gets the node at the specified index.
---@param index number The index of the node to retrieve.
---@return Turbine.UI.TreeNode # The tree node at the specified index.
function Turbine.UI.TreeNodeList:Get(index) end

---Gets the number of tree nodes.
---@return number # The number of tree nodes.
function Turbine.UI.TreeNodeList:GetCount() end

---Gets the index of a tree node in the list.
---@param node Turbine.UI.TreeNode The node to get the index of.
---@return number # The index of the node in the list or -1 if it does not exist in the list.
function Turbine.UI.TreeNodeList:IndexOf(node) end

---Removes a tree node from the list.
---@param node Turbine.UI.TreeNode The node to remove.
function Turbine.UI.TreeNodeList:Remove(node) end

---Removes a tree node at the specified index.
---@param index number The index of the node to remove.
function Turbine.UI.TreeNodeList:RemoveAt(index) end

---A control to display data in a tree.
---@class Turbine.UI.TreeView : Turbine.UI.ScrollableControl
---@field SelectedNodeChanged fun(sender: table, args: table) Event fired when the selected node has changed.
Turbine.UI.TreeView = {}

---Collapses all nodes in the tree view.
function Turbine.UI.TreeView:CollapseAll() end

---Expands all nodes in the tree view.
function Turbine.UI.TreeView:ExpandAll() end

---Gets a filter used to filter tree items.
---@return Object # The filter used to filter tree items.
function Turbine.UI.TreeView:GetFilter() end

---Gets the width of the indentation insert prefer nodes at each level in the tree.
---@return number # The width in pixels to indent nested levels of tree nodes.
function Turbine.UI.TreeView:GetIndentationWidth() end

---Gets the root nodes in the tree view control.
---@return Turbine.UI.TreeNodeList # The collection of root nodes in the tree view.
function Turbine.UI.TreeView:GetNodes() end

---Gets the currently selected node.
---@return Turbine.UI.TreeNode # The currently selected node.
function Turbine.UI.TreeView:GetSelectedNode() end

---Gets a function that is used to sort tree elements.
---@return Object # The function to sort tree elements.
function Turbine.UI.TreeView:GetSortMethod() end

---Causes the tree view to refilter and resort.
function Turbine.UI.TreeView:Refresh() end

---Sets a filter used to filter tree items.
---@param value Object The filter used to filter tree items.
function Turbine.UI.TreeView:SetFilter(value) end

---Sets the width of the indentation insert prefer nodes at each level in the tree.
---@param value number The width in pixels to indent nested levels of tree nodes.
function Turbine.UI.TreeView:SetIndentationWidth(value) end

---Sets the currently selected node.
---@param value Turbine.UI.TreeNode The node to select.
function Turbine.UI.TreeView:SetSelectedNode(value) end

---Sets a function that is used to sort tree elements.
---This function needs to enforce consistent ordering or there is a potential for a client crash.
---@param value Object The function to sort tree elements.
function Turbine.UI.TreeView:SetSortMethod(value) end

---A top level window control.
---@class Turbine.UI.Window : Turbine.UI.Control
---@field Activated fun(sender: table, args: table) Event fired when a window is activated.
---@field Closed fun(sender: table, args: table) Event fired when a window is closed.
---@field Closing fun(sender: table, args: table) Event fired when a window is closing.
---@field Deactivated fun(sender: table, args: table) Event fired when a window is deactivated.
Turbine.UI.Window = {}

---Activates a window, bringing it to the front.
function Turbine.UI.Window:Activate() end

---Closes the window.
function Turbine.UI.Window:Close() end

---Gets the maximum height of the window.
---@return number # The maximum height of the window.
function Turbine.UI.Window:GetMaximumHeight() end

---Gets the maximum size of the window.
---@return number, number # The maximum width and height as a pair of integers.
function Turbine.UI.Window:GetMaximumSize() end

---Gets the maximum width of the window.
---@return number # The maximum width of the window.
function Turbine.UI.Window:GetMaximumWidth() end

---Gets the minimum height of the window.
---@return number # The minimum height of the window.
function Turbine.UI.Window:GetMinimumHeight() end

---Gets the minimum size of the window.
---@return number, number # The minimum width and height as a pair of integers.
function Turbine.UI.Window:GetMinimumSize() end

---Gets the minimum width of the window.
---@return number # The minimum width of the window.
function Turbine.UI.Window:GetMinimumWidth() end

---Gets the text of the window.
---@return string # The text of the window.
function Turbine.UI.Window:GetText() end

---Sets the maximum height of the window.
---@param value number The maximum height of the window.
function Turbine.UI.Window:SetMaximumHeight(value) end

---Sets the maximum size of the window.
---@param width number The desired maximum width.
---@param height number The desired maximum height.
function Turbine.UI.Window:SetMaximumSize(width, height) end

---Sets the maximum width of the window.
---@param value number The maximum width of the window.
function Turbine.UI.Window:SetMaximumWidth(value) end

---Sets the minimum height of the window.
---@param value number The minimum height of the window.
function Turbine.UI.Window:SetMinimumHeight(value) end

---Sets the minimum size of the window.
---@param width number The desired minimum width.
---@param height number The desired minimum height.
function Turbine.UI.Window:SetMinimumSize(width, height) end

---Sets the minimum width of the window.
---@param value number The minimum width of the window.
function Turbine.UI.Window:SetMinimumWidth(value) end

---Sets the text of the window.
---@param value string The text of the window.
function Turbine.UI.Window:SetText(value) end
